In [1]:
import pandas as pd
import os

In [2]:
retention = pd.read_csv("../../data/01_raw/Retention.csv", encoding="cp1252")
bob = pd.read_excel("../../data/01_raw/BoB.xlsx")

In [3]:
retention.head(10)

,Case ID,Case Title,Country,Pull VAN,New VAN,VAN,Number of Contracts,Machines,Branch,Customer Account Number,...,Number of OverdueServices,CompanySize,Customer Tier,Case Origin,Case Creation Date,Resolved Time,Registered Time,Resolved Date,Registered Date,Expected Pull Date
0,CAS-32058-P6H2Z7,Service Claim,United Kingdom,0.0,0.0,0.000,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,26-09-2025 16:05,NaN,17:00:00,NaN,23-07-2025,29-Jun-26
1,CAS-32054-V6L5K1,Service Claim,United Kingdom,0.0,0.0,423.000,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,26-09-2025 16:02,NaN,17:00:00,NaN,23-07-2025,16-May-26
2,CAS-32054-V6L5K1,Service Claim,United Kingdom,0.0,0.0,352.500,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,26-09-2025 16:02,NaN,17:00:00,NaN,23-07-2025,16-May-26
3,CAS-42090-M1V1V7,SRF - Machine not used,United Kingdom,0.0,0.0,1769.760,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,31-10-2025 14:50,NaN,16:50:38,NaN,31-10-2025,30-Jan-27
4,CAS-42090-M1V1V7,SRF - Machine not used,United Kingdom,0.0,0.0,1474.800,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,31-10-2025 14:50,NaN,16:50:38,NaN,31-10-2025,30-Jan-27
5,CAS-30365-C0V8P9,Competition seen on site,United Kingdom,0.0,0.0,2369.808,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,22-09-2025 12:43,NaN,15:43:48,NaN,22-09-2025,28-Jan-27
6,CAS-30365-C0V8P9,Competition seen on site,United Kingdom,0.0,0.0,1974.840,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,22-09-2025 12:43,NaN,15:43:48,NaN,22-09-2025,28-Jan-27
7,CAS-30366-Z3S1G3,Competition seen on site,United Kingdom,0.0,0.0,18830.448,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,22-09-2025 12:45,NaN,15:45:26,NaN,22-09-2025,28-Jan-27
8,CAS-30366-Z3S1G3,Competition seen on site,United Kingdom,0.0,0.0,15692.040,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,22-09-2025 12:45,NaN,15:45:26,NaN,22-09-2025,28-Jan-27
9,CAS-30373-N6D4T0,Competition seen on site,United Kingdom,0.0,0.0,16453.296,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,22-09-2025 12:47,NaN,15:47:48,NaN,22-09-2025,28-Jan-27

In [4]:
bob.head(10)

,account_number,company_sizing,postal_code,branch,vat_number,agreement_number,agreement_start_date,agreement_end_date,renewal_type,agreement_type,...,bpg,msdyn_product_number,product_name,service_interval,unit_amount,billing_interval,billing_period,machine,machine_variant,chemistry
0,UK02-CGBA029544-L,>1000,PE1 5FQ,Elmswell,Unknown,GBC4019041-Machine Services-327311,2025-03-17,2026-03-16,Automatic Renewal,Scheduled Billing,...,17. Ultrasonic,ISK400EAA-001483-001,SK400 EAA + 400L of KLEEN7960S + Waste Rustpro...,1.0,9812.14,1.0,monthly,SK400,AA,KLEEN7960S
1,UK02-CGBA029544-L,>1000,PE1 5FQ,Elmswell,Unknown,GBC4021962-Machine Services-332280,2025-04-14,2028-04-13,Automatic Renewal,Scheduled Billing,...,17. Ultrasonic,ISK600EAA-001356-001,SK600 EAA + 600L of KLEEN7960S + Waste Rustpro...,1.0,8830.64,1.0,monthly,SK600,AA,KLEEN7960S
2,UK02-CGBA029544-L,>1000,PE1 5FQ,Elmswell,Unknown,GBC4021962-Machine Services-332282,2025-04-14,2028-04-13,Automatic Renewal,Scheduled Billing,...,17. Ultrasonic,ISK600EAA-001356-001,SK600 EAA + 600L of KLEEN7960S + Waste Rustpro...,1.0,8830.64,1.0,monthly,SK600,AA,KLEEN7960S
3,UK02-CGBA124601-L,20-49,BT71 7ET,Lisburn,GB714768220,GBC4000950-Auto waste,2022-06-24,2026-06-23,Automatic Renewal,Scheduled Billing,...,40. Oil Filters,K0000-040259-000,Waste Paint Sludge Collection - 205,0.0,7686.88,1.0,monthly,NaN,NaN,NaN
4,UK02-CGBA034502-L,50-99,BT41 3UF,Lisburn,Unknown,GBC3028394-Chemistry,2024-11-04,2025-11-03,Automatic Renewal,Scheduled Billing,...,30. Allied Products,C0000-000468-001,Delivery of Std Thinners - 205Ltrs (6),1.0,6933.91,1.0,monthly,NaN,NaN,NaN
5,UK02-CGBA110426-L,>1000,NN11 8NG,Bedford,Unknown,GBC3034379-Machine Services-306741,2022-05-31,2026-05-30,Automatic Renewal,Scheduled Billing,...,21. Automated Aqueous Multi-Stage,IM227GAA-001106-002,M227 GAA + 2000L of KLEEN7350J + Waste Aqueous...,2.0,6369.31,1.0,monthly,M227,AA,KLEEN7350J
6,UK02-SGBA013690-L,>1000,TW13 7WB,West London,GB452876421,GBC2548289-Machine Services-319822,2025-08-11,2027-08-12,Automatic Renewal,Scheduled Billing,...,01. Solvent Parts Cleaners,IM115ESV-001005-001,M115 ESV + 200L of Natural Solvent + Waste NAT...,1.0,6178.55,1.0,monthly,M115,SV,Natural Solvent
7,UK02-CGBA029544-L,>1000,PE1 5FQ,Elmswell,Unknown,GBC4019041-Machine Services-331601,2025-03-17,2026-03-16,Automatic Renewal,Scheduled Billing,...,16. Deruster,IC800XAA-001996-002,C800 + 400L of KLEEN7960S + Waste Rustpro Sol...,2.0,5520.67,1.0,monthly,C800,AA,KLEEN7960S
8,UK02-CGBA029184-L,>1000,DN4 0BF,Dinnington,Unknown,GBC4015237-Machine Services-333001,2025-05-26,2028-05-25,Automatic Renewal,Scheduled Billing,...,02. Automated Aqueous Unit,IM245FAA-001686-001,M245 FAA + 600L of KLEEN2020N + Waste SPRAYWAS...,1.0,5421.04,1.0,monthly,M245,AA,KLEEN2020N
9,UK02-SGBA034070-L,>1000,DD10 9ET,Montrose,Unknown,GBC4006291-Machine Services-329020,2024-07-24,2027-07-23,Automatic Renewal,Scheduled Billing,...,17. Ultrasonic,ISK2000FAA-001368004,SK2000 FAA + 2000L of KLEEN7960S + Waste Rustp...,4.0,5039.42,1.0,monthly,SK2000,AA,KLEEN7960S

In [5]:
# 1. Use the subset parameter to specify the columns to check for duplicates
bob = bob.drop_duplicates(subset=['account_number','agreement_number', 'agreement_start_date', 'agreement_end_date'])

# 2. To modify the original DataFrame directly without creating a new one:
bob.drop_duplicates(subset=['account_number', 'agreement_number', 'agreement_start_date', 'agreement_end_date'], inplace=True)

In [6]:
bob.isna().sum()

account_number              1
company_sizing            803
postal_code                 1
branch                      1
vat_number                143
agreement_number            1
agreement_start_date        1
agreement_end_date          1
renewal_type                1
agreement_type              1
line_of_business            1
system_status               1
product_bob                 0
fee_bob                     0
total_bob                   0
is_bob                      1
bpg                      1748
msdyn_product_number     1177
product_name             1177
service_interval         3099
unit_amount              1732
billing_interval         5079
billing_period           5079
machine                 17314
machine_variant         17311
chemistry               28523
dtype: int64

In [7]:
# List of your 4 columns
cols = ['account_number', 'agreement_number', 'agreement_start_date', 'agreement_end_date']

# Get null counts for each
null_per_col = bob[cols].isnull()
print(null_per_col.head(10))

   account_number  agreement_number  agreement_start_date  agreement_end_date
0           False             False                 False               False
1           False             False                 False               False
2           False             False                 False               False
3           False             False                 False               False
4           False             False                 False               False
5           False             False                 False               False
6           False             False                 False               False
7           False             False                 False               False
8           False             False                 False               False
9           False             False                 False               False

In [8]:
# The 4 anchor columns we checked
cols = ['account_number', 'agreement_number', 'agreement_start_date', 'agreement_end_date']

# Remove rows where any of these 4 columns have a Null value
bob.dropna(subset=cols, inplace=True)

# Verify the new row count
print(f"Rows remaining: {len(bob)}")

Rows remaining: 65883

In [9]:
# Calculate percentage of nulls for every column
null_percentage = retention.isnull().mean() * 100

# Display the results
print(null_percentage)

Case ID                        0.000000
Case Title                     0.000000
Country                        0.000000
Pull VAN                       0.000000
New VAN                        0.000000
VAN                            0.504619
Number of Contracts           16.581002
Machines                      16.581002
Branch                         9.519851
Customer Account Number        8.736580
Customer Name                  8.736580
Customer Since               100.000000
Agreement End Date             0.241187
Pull Type                     41.220686
Case Type                      0.000000
Risk                          53.136013
Current Status                 0.000000
Resolution Status              0.000000
Number Of Repair Cases        27.290396
Number of OverdueServices     27.290396
CompanySize                   27.629931
Customer Tier                 36.252942
Case Origin                   24.809451
Case Creation Date             0.000000
Resolved Time                 15.827001
Registered Time                0.000000
Resolved Date                 15.827001
Registered Date                0.000000
Expected Pull Date             0.351243
dtype: float64

In [10]:
# Since 100% null
retention = retention.drop(columns=["Customer Since"])

In [11]:
# Removes rows where the ID is null
retention.dropna(subset=['Customer Account Number'], inplace=True)

# Verify that nulls are gone
print(f"Remaining Nulls in account_number: {bob['account_number'].isnull().sum()}")

Remaining Nulls in account_number: 0

In [12]:
bob.head()

,account_number,company_sizing,postal_code,branch,vat_number,agreement_number,agreement_start_date,agreement_end_date,renewal_type,agreement_type,...,bpg,msdyn_product_number,product_name,service_interval,unit_amount,billing_interval,billing_period,machine,machine_variant,chemistry
0,UK02-CGBA029544-L,>1000,PE1 5FQ,Elmswell,Unknown,GBC4019041-Machine Services-327311,2025-03-17,2026-03-16,Automatic Renewal,Scheduled Billing,...,17. Ultrasonic,ISK400EAA-001483-001,SK400 EAA + 400L of KLEEN7960S + Waste Rustpro...,1.0,9812.14,1.0,monthly,SK400,AA,KLEEN7960S
1,UK02-CGBA029544-L,>1000,PE1 5FQ,Elmswell,Unknown,GBC4021962-Machine Services-332280,2025-04-14,2028-04-13,Automatic Renewal,Scheduled Billing,...,17. Ultrasonic,ISK600EAA-001356-001,SK600 EAA + 600L of KLEEN7960S + Waste Rustpro...,1.0,8830.64,1.0,monthly,SK600,AA,KLEEN7960S
2,UK02-CGBA029544-L,>1000,PE1 5FQ,Elmswell,Unknown,GBC4021962-Machine Services-332282,2025-04-14,2028-04-13,Automatic Renewal,Scheduled Billing,...,17. Ultrasonic,ISK600EAA-001356-001,SK600 EAA + 600L of KLEEN7960S + Waste Rustpro...,1.0,8830.64,1.0,monthly,SK600,AA,KLEEN7960S
3,UK02-CGBA124601-L,20-49,BT71 7ET,Lisburn,GB714768220,GBC4000950-Auto waste,2022-06-24,2026-06-23,Automatic Renewal,Scheduled Billing,...,40. Oil Filters,K0000-040259-000,Waste Paint Sludge Collection - 205,0.0,7686.88,1.0,monthly,NaN,NaN,NaN
4,UK02-CGBA034502-L,50-99,BT41 3UF,Lisburn,Unknown,GBC3028394-Chemistry,2024-11-04,2025-11-03,Automatic Renewal,Scheduled Billing,...,30. Allied Products,C0000-000468-001,Delivery of Std Thinners - 205Ltrs (6),1.0,6933.91,1.0,monthly,NaN,NaN,NaN

In [13]:
# Shows all rows that have an identical twin elsewhere in the data
duplicate_rows = retention[retention.duplicated(keep=False)]
duplicate_rows.sort_values(by='Case ID').head(10)

,Case ID,Case Title,Country,Pull VAN,New VAN,VAN,Number of Contracts,Machines,Branch,Customer Account Number,...,Number of OverdueServices,CompanySize,Customer Tier,Case Origin,Case Creation Date,Resolved Time,Registered Time,Resolved Date,Registered Date,Expected Pull Date
26326,CAS-03396-W1B7T8,Risk - contract enquiry,United Kingdom,0.0,0.0,0.0,2.0,2.0,Laindon,UK02-CGBA011376-L,...,0.0,50-99,Platinum,Credit Controller,15-09-2021 12:10,10:44:48,14:10:24,28-09-2021,15-09-2021,24-Mar-22
26325,CAS-03396-W1B7T8,Risk - contract enquiry,United Kingdom,0.0,0.0,0.0,2.0,2.0,Laindon,UK02-CGBA011376-L,...,0.0,50-99,Platinum,Credit Controller,15-09-2021 12:10,10:44:48,14:10:24,28-09-2021,15-09-2021,24-Mar-22
26609,CAS-03418-N3R7M3,Original Risk Case: RISK,United Kingdom,0.0,0.0,0.0,1.0,4.0,Dinnington,UK02-CGBA027080-L,...,0.0,NaN,NaN,Risk Case,16-09-2021 05:44,08:36:56,07:44:53,08-11-2021,16-09-2021,20-Sep-21
26608,CAS-03418-N3R7M3,Original Risk Case: RISK,United Kingdom,0.0,0.0,0.0,1.0,4.0,Dinnington,UK02-CGBA027080-L,...,0.0,NaN,NaN,Risk Case,16-09-2021 05:44,08:36:56,07:44:53,08-11-2021,16-09-2021,20-Sep-21
23493,CAS-03450-Y4V5P2,Cancellation - partial - process change,United Kingdom,0.0,0.0,0.0,5.0,35.0,Dinnington,UK02-CGBA026544-L,...,0.0,>=1000,Key Account,Account Manager,16-09-2021 11:46,12:32:03,13:46:17,23-09-2021,16-09-2021,20-Dec-21
23511,CAS-03450-Y4V5P2,Cancellation - partial - process change,United Kingdom,0.0,0.0,0.0,5.0,35.0,Dinnington,UK02-CGBA026544-L,...,0.0,>=1000,Key Account,Account Manager,16-09-2021 11:46,12:32:03,13:46:17,23-09-2021,16-09-2021,20-Dec-21
27992,CAS-03479-R4Q3Z9,Original Complaint Case: CR SURVEY - NEGATIVE ...,United Kingdom,0.0,0.0,0.0,1.0,2.0,Montrose,UK02-CGBA033804-L,...,0.0,NaN,NaN,Complaint Case,17-09-2021 08:03,18:02:18,10:03:08,23-09-2021,17-09-2021,25-Oct-21
27993,CAS-03479-R4Q3Z9,Original Complaint Case: CR SURVEY - NEGATIVE ...,United Kingdom,0.0,0.0,0.0,1.0,2.0,Montrose,UK02-CGBA033804-L,...,0.0,NaN,NaN,Complaint Case,17-09-2021 08:03,18:02:18,10:03:08,23-09-2021,17-09-2021,25-Oct-21
27427,CAS-03597-B6F2B0,Original Risk Case: Cancellation - R1 - Legal ...,United Kingdom,0.0,0.0,0.0,1.0,1.0,Chester,UK02-CGBA116927-L,...,0.0,NaN,NaN,Risk Case,22-09-2021 09:24,08:36:09,11:24:10,08-11-2021,22-09-2021,30-Sep-21
27426,CAS-03597-B6F2B0,Original Risk Case: Cancellation - R1 - Legal ...,United Kingdom,0.0,0.0,0.0,1.0,1.0,Chester,UK02-CGBA116927-L,...,0.0,NaN,NaN,Risk Case,22-09-2021 09:24,08:36:09,11:24:10,08-11-2021,22-09-2021,30-Sep-21

In [14]:
# 1. Use the subset parameter to specify the columns to check for duplicates
retention = retention.drop_duplicates(subset=['Case ID', 'Customer Account Number','Case Title'])

In [15]:
retention.isna().sum()

Case ID                          0
Case Title                       0
Country                          0
Pull VAN                         0
New VAN                          0
VAN                            117
Number of Contracts          11949
Machines                     11949
Branch                         764
Customer Account Number          0
Customer Name                    0
Agreement End Date              97
Pull Type                    22050
Case Type                        0
Risk                         21651
Current Status                   0
Resolution Status                0
Number Of Repair Cases        6722
Number of OverdueServices     6722
CompanySize                  13128
Customer Tier                15993
Case Origin                  11720
Case Creation Date               0
Resolved Time                 4039
Registered Time                  0
Resolved Date                 4039
Registered Date                  0
Expected Pull Date             162
dtype: int64

In [17]:
# Assuming your existing folder is named 'Data_Exports'
folder_path = '../../data/02_intermediate'

# Save the first dataframe
retention.to_csv(f'{folder_path}/retention_data.csv', index=False)

# Save the second dataframe
bob.to_csv(f'{folder_path}/bob_data.csv', index=False)

print("Both files have been saved to the existing folder.")

Both files have been saved to the existing folder.