# Preprocessing Notebook

In [1]:
import pandas as pd

In [8]:
retention = pd.read_csv("../../data/01_raw/Retention.csv", encoding="cp1252")
bob = pd.read_excel("../../data/01_raw/BoB.xlsx")

In [9]:
retention.head(10)

,Case ID,Case Title,Country,Pull VAN,New VAN,VAN,Number of Contracts,Machines,Branch,Customer Account Number,...,Number of OverdueServices,CompanySize,Customer Tier,Case Origin,Case Creation Date,Resolved Time,Registered Time,Resolved Date,Registered Date,Expected Pull Date
0,CAS-32058-P6H2Z7,Service Claim,United Kingdom,0.0,0.0,0.000,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,26-09-2025 16:05,NaN,17:00:00,NaN,23-07-2025,29-Jun-26
1,CAS-32054-V6L5K1,Service Claim,United Kingdom,0.0,0.0,423.000,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,26-09-2025 16:02,NaN,17:00:00,NaN,23-07-2025,16-May-26
2,CAS-32054-V6L5K1,Service Claim,United Kingdom,0.0,0.0,352.500,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,26-09-2025 16:02,NaN,17:00:00,NaN,23-07-2025,16-May-26
3,CAS-42090-M1V1V7,SRF - Machine not used,United Kingdom,0.0,0.0,1769.760,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,31-10-2025 14:50,NaN,16:50:38,NaN,31-10-2025,30-Jan-27
4,CAS-42090-M1V1V7,SRF - Machine not used,United Kingdom,0.0,0.0,1474.800,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,31-10-2025 14:50,NaN,16:50:38,NaN,31-10-2025,30-Jan-27
5,CAS-30365-C0V8P9,Competition seen on site,United Kingdom,0.0,0.0,2369.808,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,22-09-2025 12:43,NaN,15:43:48,NaN,22-09-2025,28-Jan-27
6,CAS-30365-C0V8P9,Competition seen on site,United Kingdom,0.0,0.0,1974.840,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,22-09-2025 12:43,NaN,15:43:48,NaN,22-09-2025,28-Jan-27
7,CAS-30366-Z3S1G3,Competition seen on site,United Kingdom,0.0,0.0,18830.448,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,22-09-2025 12:45,NaN,15:45:26,NaN,22-09-2025,28-Jan-27
8,CAS-30366-Z3S1G3,Competition seen on site,United Kingdom,0.0,0.0,15692.040,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,22-09-2025 12:45,NaN,15:45:26,NaN,22-09-2025,28-Jan-27
9,CAS-30373-N6D4T0,Competition seen on site,United Kingdom,0.0,0.0,16453.296,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,22-09-2025 12:47,NaN,15:47:48,NaN,22-09-2025,28-Jan-27

In [10]:
bob.head(10)

,account_number,company_sizing,postal_code,branch,vat_number,agreement_number,agreement_start_date,agreement_end_date,renewal_type,agreement_type,...,bpg,msdyn_product_number,product_name,service_interval,unit_amount,billing_interval,billing_period,machine,machine_variant,chemistry
0,UK02-CGBA029544-L,>1000,PE1 5FQ,Elmswell,Unknown,GBC4019041-Machine Services-327311,2025-03-17,2026-03-16,Automatic Renewal,Scheduled Billing,...,17. Ultrasonic,ISK400EAA-001483-001,SK400 EAA + 400L of KLEEN7960S + Waste Rustpro...,1.0,9812.14,1.0,monthly,SK400,AA,KLEEN7960S
1,UK02-CGBA029544-L,>1000,PE1 5FQ,Elmswell,Unknown,GBC4021962-Machine Services-332280,2025-04-14,2028-04-13,Automatic Renewal,Scheduled Billing,...,17. Ultrasonic,ISK600EAA-001356-001,SK600 EAA + 600L of KLEEN7960S + Waste Rustpro...,1.0,8830.64,1.0,monthly,SK600,AA,KLEEN7960S
2,UK02-CGBA029544-L,>1000,PE1 5FQ,Elmswell,Unknown,GBC4021962-Machine Services-332282,2025-04-14,2028-04-13,Automatic Renewal,Scheduled Billing,...,17. Ultrasonic,ISK600EAA-001356-001,SK600 EAA + 600L of KLEEN7960S + Waste Rustpro...,1.0,8830.64,1.0,monthly,SK600,AA,KLEEN7960S
3,UK02-CGBA124601-L,20-49,BT71 7ET,Lisburn,GB714768220,GBC4000950-Auto waste,2022-06-24,2026-06-23,Automatic Renewal,Scheduled Billing,...,40. Oil Filters,K0000-040259-000,Waste Paint Sludge Collection - 205,0.0,7686.88,1.0,monthly,NaN,NaN,NaN
4,UK02-CGBA034502-L,50-99,BT41 3UF,Lisburn,Unknown,GBC3028394-Chemistry,2024-11-04,2025-11-03,Automatic Renewal,Scheduled Billing,...,30. Allied Products,C0000-000468-001,Delivery of Std Thinners - 205Ltrs (6),1.0,6933.91,1.0,monthly,NaN,NaN,NaN
5,UK02-CGBA110426-L,>1000,NN11 8NG,Bedford,Unknown,GBC3034379-Machine Services-306741,2022-05-31,2026-05-30,Automatic Renewal,Scheduled Billing,...,21. Automated Aqueous Multi-Stage,IM227GAA-001106-002,M227 GAA + 2000L of KLEEN7350J + Waste Aqueous...,2.0,6369.31,1.0,monthly,M227,AA,KLEEN7350J
6,UK02-SGBA013690-L,>1000,TW13 7WB,West London,GB452876421,GBC2548289-Machine Services-319822,2025-08-11,2027-08-12,Automatic Renewal,Scheduled Billing,...,01. Solvent Parts Cleaners,IM115ESV-001005-001,M115 ESV + 200L of Natural Solvent + Waste NAT...,1.0,6178.55,1.0,monthly,M115,SV,Natural Solvent
7,UK02-CGBA029544-L,>1000,PE1 5FQ,Elmswell,Unknown,GBC4019041-Machine Services-331601,2025-03-17,2026-03-16,Automatic Renewal,Scheduled Billing,...,16. Deruster,IC800XAA-001996-002,C800 + 400L of KLEEN7960S + Waste Rustpro Sol...,2.0,5520.67,1.0,monthly,C800,AA,KLEEN7960S
8,UK02-CGBA029184-L,>1000,DN4 0BF,Dinnington,Unknown,GBC4015237-Machine Services-333001,2025-05-26,2028-05-25,Automatic Renewal,Scheduled Billing,...,02. Automated Aqueous Unit,IM245FAA-001686-001,M245 FAA + 600L of KLEEN2020N + Waste SPRAYWAS...,1.0,5421.04,1.0,monthly,M245,AA,KLEEN2020N
9,UK02-SGBA034070-L,>1000,DD10 9ET,Montrose,Unknown,GBC4006291-Machine Services-329020,2024-07-24,2027-07-23,Automatic Renewal,Scheduled Billing,...,17. Ultrasonic,ISK2000FAA-001368004,SK2000 FAA + 2000L of KLEEN7960S + Waste Rustp...,4.0,5039.42,1.0,monthly,SK2000,AA,KLEEN7960S