# Exploration Notebook

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from pathlib import Path
from src.cleaning.basiccleaning import clean_cols

ModuleNotFoundError: No module named 'src'

In [ ]:
BASE_DIR = Path().resolve().parents[1]

RAW_DATA = BASE_DIR / "data" / "01_raw"
INTERIM_DATA = BASE_DIR / "data" / "02_interim"

bob = pd.read_csv(RAW_DATA / "BoB.csv",encoding="latin1")
retention = pd.read_csv(RAW_DATA / "Retention.csv",encoding="latin1")

In [10]:
bob.head()

,ï»¿account_number,company_sizing,postal_code,branch,vat_number,agreement_number,agreement_start_date,agreement_end_date,renewal_type,agreement_type,...,bpg,msdyn_product_number,product_name,service_interval,unit_amount,billing_interval,billing_period,machine,machine_variant,chemistry
0,UK02-CGBA029544-L,>1000,PE1 5FQ,Elmswell,Unknown,GBC4019041-Machine Services-327311,2025-03-17 00:00:00,2026-03-16 00:00:00,Automatic Renewal,Scheduled Billing,...,17. Ultrasonic,ISK400EAA-001483-001,SK400 EAA + 400L of KLEEN7960S + Waste Rustpro...,1.0,9812.14,1.0,monthly,SK400,AA,KLEEN7960S
1,UK02-CGBA029544-L,>1000,PE1 5FQ,Elmswell,Unknown,GBC4021962-Machine Services-332280,2025-04-14 00:00:00,2028-04-13 00:00:00,Automatic Renewal,Scheduled Billing,...,17. Ultrasonic,ISK600EAA-001356-001,SK600 EAA + 600L of KLEEN7960S + Waste Rustpro...,1.0,8830.64,1.0,monthly,SK600,AA,KLEEN7960S
2,UK02-CGBA029544-L,>1000,PE1 5FQ,Elmswell,Unknown,GBC4021962-Machine Services-332282,2025-04-14 00:00:00,2028-04-13 00:00:00,Automatic Renewal,Scheduled Billing,...,17. Ultrasonic,ISK600EAA-001356-001,SK600 EAA + 600L of KLEEN7960S + Waste Rustpro...,1.0,8830.64,1.0,monthly,SK600,AA,KLEEN7960S
3,UK02-CGBA124601-L,20-49,BT71 7ET,Lisburn,GB714768220,GBC4000950-Auto waste,2022-06-24 00:00:00,2026-06-23 00:00:00,Automatic Renewal,Scheduled Billing,...,40. Oil Filters,K0000-040259-000,Waste Paint Sludge Collection - 205,0.0,7686.88,1.0,monthly,NaN,NaN,NaN
4,UK02-CGBA034502-L,50-99,BT41 3UF,Lisburn,Unknown,GBC3028394-Chemistry,2024-11-04 00:00:00,2025-11-03 00:00:00,Automatic Renewal,Scheduled Billing,...,30. Allied Products,C0000-000468-001,Delivery of Std Thinners - 205Ltrs (6),1.0,6933.91,1.0,monthly,NaN,NaN,NaN

In [12]:
retention.head()

,Case ID,Case Title,Country,Pull VAN,New VAN,VAN,Number of Contracts,Machines,Branch,Customer Account Number,...,Number of OverdueServices,CompanySize,Customer Tier,Case Origin,Case Creation Date,Resolved Time,Registered Time,Resolved Date,Registered Date,Expected Pull Date
0,CAS-32058-P6H2Z7,Service Claim,United Kingdom,0.0,0.0,0.00,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,26-09-2025 16:05,NaN,17:00:00,NaN,23-07-2025,29-Jun-26
1,CAS-32054-V6L5K1,Service Claim,United Kingdom,0.0,0.0,423.00,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,26-09-2025 16:02,NaN,17:00:00,NaN,23-07-2025,16-May-26
2,CAS-32054-V6L5K1,Service Claim,United Kingdom,0.0,0.0,352.50,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,26-09-2025 16:02,NaN,17:00:00,NaN,23-07-2025,16-May-26
3,CAS-42090-M1V1V7,SRF - Machine not used,United Kingdom,0.0,0.0,1769.76,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,31-10-2025 14:50,NaN,16:50:38,NaN,31-10-2025,30-Jan-27
4,CAS-42090-M1V1V7,SRF - Machine not used,United Kingdom,0.0,0.0,1474.80,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,Internal Email,31-10-2025 14:50,NaN,16:50:38,NaN,31-10-2025,30-Jan-27

In [21]:
bob.columns

Index(['account_number', 'company_sizing', 'postal_code', 'branch',
       'vat_number', 'agreement_number', 'agreement_start_date',
       'agreement_end_date', 'renewal_type', 'agreement_type',
       'line_of_business', 'system_status', 'product_bob', 'fee_bob',
       'total_bob', 'is_bob', 'bpg', 'msdyn_product_number', 'product_name',
       'service_interval', 'unit_amount', 'billing_interval', 'billing_period',
       'machine', 'machine_variant', 'chemistry'],
      dtype='str')

In [17]:
retention.columns

Index(['Case ID', 'Case Title', 'Country', 'Pull VAN', 'New VAN', 'VAN',
       'Number of Contracts', 'Machines', 'Branch', 'Customer Account Number',
       'Customer Name', 'Customer Since', 'Agreement End Date', 'Pull Type',
       'Case Type', 'Risk', 'Current Status', 'Resolution Status',
       'Number Of Repair Cases', 'Number of OverdueServices', 'CompanySize',
       'Customer Tier', 'Case Origin', 'Case Creation Date', 'Resolved Time',
       'Registered Time', 'Resolved Date', 'Registered Date',
       'Expected Pull Date'],
      dtype='str')

In [ ]:
bob = clean_cols(bob)
retention = clean_cols(retention)

In [20]:
bob = bob.rename(columns={"ï»¿account_number": "account_number"})

In [1]:
bob.to_csv(INTERIM_DATA / "bob_interim.csv", index=False)
retention.to_csv(INTERIM_DATA / "retention_interim.csv", index=False)

NameError: name 'bob' is not defined